// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/department/department.proto

package department

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Department struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent               int64    `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Manages              string   `protobuf:"bytes,5,opt,name=manages,proto3" json:"manages,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_a231da9bf7b7101c, []int{0}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Department) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Department) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Department) GetManages() string {
	if m != nil {
		return m.Manages
	}
	return ""
}

func (m *Department) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Department) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ListQuery struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Parent               string   `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListQuery) Reset()         { *m = ListQuery{} }
func (m *ListQuery) String() string { return proto.CompactTextString(m) }
func (*ListQuery) ProtoMessage()    {}
func (*ListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a231da9bf7b7101c, []int{1}
}

func (m *ListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListQuery.Unmarshal(m, b)
}
func (m *ListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListQuery.Marshal(b, m, deterministic)
}
func (m *ListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListQuery.Merge(m, src)
}
func (m *ListQuery) XXX_Size() int {
	return xxx_messageInfo_ListQuery.Size(m)
}
func (m *ListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ListQuery proto.InternalMessageInfo

func (m *ListQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListQuery) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListQuery) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *ListQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListQuery) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a231da9bf7b7101c, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Department           *Department   `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	Departments          []*Department `protobuf:"bytes,2,rep,name=departments,proto3" json:"departments,omitempty"`
	Total                int64         `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Valid                bool          `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a231da9bf7b7101c, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetDepartment() *Department {
	if m != nil {
		return m.Department
	}
	return nil
}

func (m *Response) GetDepartments() []*Department {
	if m != nil {
		return m.Departments
	}
	return nil
}

func (m *Response) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Department)(nil), "department.Department")
	proto.RegisterType((*ListQuery)(nil), "department.ListQuery")
	proto.RegisterType((*Request)(nil), "department.Request")
	proto.RegisterType((*Response)(nil), "department.Response")
}

func init() { proto.RegisterFile("proto/department/department.proto", fileDescriptor_a231da9bf7b7101c) }

var fileDescriptor_a231da9bf7b7101c = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4b, 0x6a, 0xe3, 0x40,
	0x14, 0x1c, 0x49, 0xb6, 0x6c, 0x3d, 0xc3, 0x2c, 0x1a, 0x8f, 0x69, 0x06, 0x06, 0x3c, 0x5a, 0x79,
	0xe5, 0x80, 0x83, 0x83, 0xb7, 0x26, 0x86, 0x6c, 0xb2, 0x89, 0x20, 0xeb, 0xd0, 0x89, 0x1e, 0x8e,
	0x40, 0xbf, 0xa8, 0x9f, 0x03, 0x39, 0x40, 0xee, 0x92, 0x13, 0xe4, 0x3c, 0x39, 0x4a, 0xe8, 0x8f,
	0xac, 0x4e, 0x20, 0x06, 0x7b, 0xf7, 0xaa, 0x4a, 0x45, 0x57, 0xf5, 0x6b, 0xc1, 0xff, 0xba, 0xa9,
	0xa8, 0x3a, 0x4b, 0xb1, 0x16, 0x0d, 0x15, 0x58, 0x92, 0x33, 0xce, 0xb5, 0xc6, 0xa0, 0x63, 0xe2,
	0x77, 0x0f, 0x60, 0xb3, 0x87, 0xec, 0x37, 0xf8, 0x59, 0xca, 0xbd, 0xa9, 0x37, 0x0b, 0x12, 0x3f,
	0x4b, 0xd9, 0x04, 0xc2, 0x5a, 0x34, 0x58, 0x12, 0xf7, 0x35, 0x67, 0x11, 0x63, 0xd0, 0x2b, 0x45,
	0x81, 0x3c, 0x98, 0x7a, 0xb3, 0x28, 0xd1, 0x33, 0x1b, 0x43, 0xbf, 0x7e, 0xac, 0x4a, 0xe4, 0x3d,
	0x4d, 0x1a, 0xc0, 0x38, 0x0c, 0x0a, 0x51, 0x8a, 0x2d, 0x4a, 0xde, 0xd7, 0x7c, 0x0b, 0xd9, 0x3f,
	0x80, 0x87, 0x06, 0x05, 0x61, 0x7a, 0x27, 0x88, 0x87, 0x5a, 0x8c, 0x2c, 0xb3, 0x26, 0x25, 0xef,
	0xea, 0xb4, 0x95, 0x07, 0x46, 0xb6, 0xcc, 0x9a, 0xe2, 0x57, 0x0f, 0xa2, 0xeb, 0x4c, 0xd2, 0xcd,
	0x0e, 0x9b, 0x17, 0x75, 0x76, 0x9e, 0x15, 0x19, 0xd9, 0xe8, 0x06, 0xa8, 0x94, 0xb5, 0xd8, 0xa2,
	0xcd, 0xae, 0x67, 0xc5, 0xc9, 0xaa, 0xa1, 0x36, 0xb9, 0x9a, 0x6d, 0x6b, 0x13, 0xfb, 0x6b, 0x6b,
	0x13, 0xf9, 0x7b, 0xeb, 0xb0, 0x6b, 0x1d, 0x47, 0x30, 0x48, 0xf0, 0x69, 0x87, 0x92, 0xe2, 0x37,
	0x0f, 0x86, 0x09, 0xca, 0xba, 0x2a, 0x25, 0xb2, 0x0b, 0x70, 0xae, 0x59, 0xc7, 0x1a, 0x2d, 0x26,
	0x73, 0x67, 0x17, 0xdd, 0xad, 0x27, 0xce, 0x97, 0x6c, 0x05, 0xa3, 0x0e, 0x49, 0xee, 0x4f, 0x83,
	0x03, 0x46, 0xf7, 0x53, 0x75, 0x07, 0x54, 0x91, 0xc8, 0x75, 0xb5, 0x20, 0x31, 0x40, 0xb1, 0xcf,
	0x22, 0xb7, 0xf5, 0x86, 0x89, 0x01, 0x8b, 0x0f, 0x1f, 0x46, 0x1b, 0xc7, 0xbb, 0x84, 0x60, 0x9d,
	0xe7, 0xec, 0x87, 0x73, 0xfe, 0x8e, 0x5d, 0xbe, 0xad, 0x18, 0xff, 0x62, 0x4b, 0xe8, 0xa9, 0x1d,
	0xb0, 0x3f, 0xae, 0xbe, 0xdf, 0xca, 0x01, 0x5b, 0x70, 0x85, 0x74, 0xf4, 0x69, 0x2b, 0x08, 0x2f,
	0xf5, 0xf3, 0x38, 0xc5, 0x79, 0xab, 0x5f, 0xce, 0x29, 0xce, 0x0d, 0xe6, 0x78, 0xbc, 0xf3, 0x3e,
	0xd4, 0x3f, 0xdb, 0xf9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x4d, 0xca, 0x7b, 0x91, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Departments service

type DepartmentsClient interface {
	// 全部部门列
	All(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error)
	// 获取部门列表
	List(ctx context.Context, in *ListQuery, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取部门
	Get(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error)
	// 创建部门
	Create(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error)
	// 更新部门
	Update(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error)
	// 删除部门
	Delete(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error)
}

type departmentsClient struct {
	c           client.Client
	serviceName string
}

func NewDepartmentsClient(serviceName string, c client.Client) DepartmentsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "department"
	}
	return &departmentsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *departmentsClient) All(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Departments.All", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentsClient) List(ctx context.Context, in *ListQuery, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Departments.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentsClient) Get(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Departments.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentsClient) Create(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Departments.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentsClient) Update(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Departments.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departmentsClient) Delete(ctx context.Context, in *Department, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Departments.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Departments service

type DepartmentsHandler interface {
	// 全部部门列
	All(context.Context, *Department, *Response) error
	// 获取部门列表
	List(context.Context, *ListQuery, *Response) error
	// 根据 唯一 获取部门
	Get(context.Context, *Department, *Response) error
	// 创建部门
	Create(context.Context, *Department, *Response) error
	// 更新部门
	Update(context.Context, *Department, *Response) error
	// 删除部门
	Delete(context.Context, *Department, *Response) error
}

func RegisterDepartmentsHandler(s server.Server, hdlr DepartmentsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Departments{hdlr}, opts...))
}

type Departments struct {
	DepartmentsHandler
}

func (h *Departments) All(ctx context.Context, in *Department, out *Response) error {
	return h.DepartmentsHandler.All(ctx, in, out)
}

func (h *Departments) List(ctx context.Context, in *ListQuery, out *Response) error {
	return h.DepartmentsHandler.List(ctx, in, out)
}

func (h *Departments) Get(ctx context.Context, in *Department, out *Response) error {
	return h.DepartmentsHandler.Get(ctx, in, out)
}

func (h *Departments) Create(ctx context.Context, in *Department, out *Response) error {
	return h.DepartmentsHandler.Create(ctx, in, out)
}

func (h *Departments) Update(ctx context.Context, in *Department, out *Response) error {
	return h.DepartmentsHandler.Update(ctx, in, out)
}

func (h *Departments) Delete(ctx context.Context, in *Department, out *Response) error {
	return h.DepartmentsHandler.Delete(ctx, in, out)
}
